### PR TITLE
fix: issue #5, getReportDate test failed

### PR DESCRIPTION
**Pull request by schalkneethling**
@alexgibson r?

### CODE REVIEW

**Comment by alexgibson** [comment]
Not quite sure what the issue is here, but the last commit to master passed OK: https://travis-ci.org/mozmeao/performance-dashboard/builds/367039747

**Comment by alexgibson** [comment]
Tests pass for me locally on master too, but the changes in the PR here failed?

**Comment by schalkneethling** [comment]
@alexgibson That is very strange indeed. Without this change running either `build` or `start` fails for me :-/ Could it somehow be a system clock thing? It does not make sense but, maybe?

**Comment by alexgibson** [comment]
I wonder if it's a local time thing perhaps - maybe we need to use UTC?

**Comment by alexgibson** [comment]
I think the best solution here may be to pass in a date string for the test instead of an integer value e.g.

```
expect(summary.getReportDate('February 27, 2018 11:34:00')).toEqual('2018-02-27T11:34');
```

**Comment by alexgibson** [comment]
Thanks @schalkneethling 💯

**Pull request merged**
